name: deploy to environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      dir:
        required: true
      host:
        required: true
      port:
        required: true
      user:
        required: true
      key:
        required: true
      php_path:
        required: true
      cf_cache_purge_token:
        required: true
      cf_ztl_zone:
        required: true
      url:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: retrieve artifact for deploy
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}

      - name: extract artifact
        run: |
          tar -zxvf ${{ inputs.artifact-name }}.tar.gz
          rm ${{ inputs.artifact-name }}.tar.gz

      - name: Setup composer and install packages
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: gd zip

      - name: put server in maintenance mode
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.dir }} && ${{ secrets.php_path }} artisan down
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          username: ${{ secrets.user }}
          privateKey: ${{ secrets.key }}

      - name: push to server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzP
          path: .
          remote_path: ${{ secrets.dir }}
          remote_host: ${{ secrets.host }}
          remote_user: ${{ secrets.user }}
          remote_key: ${{ secrets.key }}

      - name: run migrations
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.dir }} && ${{ secrets.php_path }} artisan migrate --no-interaction --force
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          username: ${{ secrets.user }}
          privateKey: ${{ secrets.key }}

      - name: recache config
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.dir }} && ${{ secrets.php_path }} artisan config:cache
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          username: ${{ secrets.user }}
          privateKey: ${{ secrets.key }}

      - name: take server out of maintenance mode
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.dir }} && ${{ secrets.php_path }} artisan up
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          username: ${{ secrets.user }}
          privateKey: ${{ secrets.key }}

  clear-cloudflare-asset-cache:
    runs-on: ubuntu-latest
    container: curlimages/curl
    environment: ${{ inputs.environment }}
    needs: deploy

    steps:
      - name: clear cloudflare asset cache
        run: |
          curl \
          --request POST \
          --url https://api.cloudflare.com/client/v4/zones/${{ secrets.cf_ztl_zone }}/purge_cache \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.cf_cache_purge_token }}' \
          --data '{ "files": [ "${{ secrets.url }}/css/app.css", "${{ secrets.url }}/js/app.js" ] }'

